export interface ThemeConfig {
  key: string;
  nameEn: string;
  nameAr: string;
  mainBg: string;
  linkBg: string;
  linkBorder: string;
  linkHoverBorder: string;
  linkText: string;
  payCardBg: string;
  payCardBorder: string;
  payInstaBg: string;
  payInstaBorder: string;
  payInstaIconBg: string;
  payInstaIconText: string;
  payWalletBg: string;
  payWalletBorder: string;
  payWalletIconBg: string;
  payWalletIconText: string;
  logoBorder: string;
  langBtnBorder: string;
  langBtnBg: string;
  primaryColor: string; // E.g., 'text-slate-400' or 'text-amber-500'
  textColor: string;        // E.g., 'text-white' or 'text-slate-800'
  subTextColor: string;     // E.g., 'text-slate-400' or 'text-slate-500'
  companyNameColor: string; // E.g., 'from-white via-white to-slate-300' or 'from-slate-900 to-slate-850'
  cardTitleColor: string;   // E.g., 'text-slate-300' or 'text-slate-700'
}

export const THEMES: ThemeConfig[] = [
  {
    key: "theme1",
    nameEn: "Theme 1",
    nameAr: "ثيم 1",
    mainBg: "from-slate-900 via-slate-950 to-slate-900",
    linkBg: "bg-slate-800/50 hover:bg-slate-800",
    linkBorder: "border-slate-700/50",
    linkHoverBorder: "hover:border-slate-500/40",
    linkText: "text-slate-100",
    payCardBg: "bg-slate-800/20",
    payCardBorder: "border-slate-700/40",
    payInstaBg: "bg-slate-800/40 border border-slate-700/40 hover:bg-slate-800/60",
    payInstaBorder: "border-slate-700/40",
    payInstaIconBg: "bg-slate-800",
    payInstaIconText: "text-slate-200",
    payWalletBg: "bg-slate-800/30 border border-slate-700/40",
    payWalletBorder: "border-slate-700/40",
    payWalletIconBg: "bg-slate-800",
    payWalletIconText: "text-slate-200",
    logoBorder: "border-slate-800/50",
    langBtnBorder: "border-slate-700/40",
    langBtnBg: "bg-slate-800/80 hover:bg-slate-700",
    primaryColor: "text-slate-400",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-white to-slate-300",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme2",
    nameEn: "Theme 2",
    nameAr: "ثيم 2",
    mainBg: "from-emerald-950 via-teal-950 to-emerald-950",
    linkBg: "bg-emerald-900/20 hover:bg-emerald-900/30",
    linkBorder: "border-emerald-500/20",
    linkHoverBorder: "hover:border-emerald-400/50",
    linkText: "text-emerald-50",
    payCardBg: "bg-emerald-900/10",
    payCardBorder: "border-emerald-800/30",
    payInstaBg: "bg-emerald-500/10 border border-emerald-500/20 hover:bg-emerald-500/20",
    payInstaBorder: "border-emerald-500/20",
    payInstaIconBg: "bg-emerald-500/20",
    payInstaIconText: "text-emerald-400",
    payWalletBg: "bg-teal-900/20 border border-teal-500/20",
    payWalletBorder: "border-teal-500/20",
    payWalletIconBg: "bg-teal-950",
    payWalletIconText: "text-teal-400",
    logoBorder: "border-emerald-500/30",
    langBtnBorder: "border-emerald-500/30",
    langBtnBg: "bg-emerald-900/40 hover:bg-emerald-800/40",
    primaryColor: "text-emerald-400",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-white to-slate-300",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme3",
    nameEn: "Theme 3",
    nameAr: "ثيم 3",
    mainBg: "from-indigo-950 via-purple-950 to-slate-950",
    linkBg: "bg-purple-900/20 hover:bg-purple-900/30",
    linkBorder: "border-purple-500/20",
    linkHoverBorder: "hover:border-purple-400/50",
    linkText: "text-purple-50",
    payCardBg: "bg-purple-900/10",
    payCardBorder: "border-purple-800/30",
    payInstaBg: "bg-purple-500/10 border border-purple-500/20 hover:bg-purple-500/20",
    payInstaBorder: "border-purple-500/20",
    payInstaIconBg: "bg-purple-500/20",
    payInstaIconText: "text-purple-400",
    payWalletBg: "bg-indigo-900/20 border border-indigo-500/20",
    payWalletBorder: "border-indigo-500/20",
    payWalletIconBg: "bg-indigo-950",
    payWalletIconText: "text-indigo-400",
    logoBorder: "border-purple-500/30",
    langBtnBorder: "border-purple-500/30",
    langBtnBg: "bg-purple-900/40 hover:bg-purple-800/40",
    primaryColor: "text-purple-400",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-white to-slate-300",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme4",
    nameEn: "Theme 4",
    nameAr: "ثيم 4",
    mainBg: "from-slate-950 via-blue-950 to-slate-950",
    linkBg: "bg-blue-950/40 hover:bg-blue-900/30",
    linkBorder: "border-amber-500/20",
    linkHoverBorder: "hover:border-amber-400/50",
    linkText: "text-amber-50",
    payCardBg: "bg-blue-900/10",
    payCardBorder: "border-blue-800/30",
    payInstaBg: "bg-amber-500/10 border border-amber-500/20 hover:bg-amber-500/20",
    payInstaBorder: "border-amber-500/20",
    payInstaIconBg: "bg-amber-500/20",
    payInstaIconText: "text-amber-400",
    payWalletBg: "bg-blue-950/50 border border-amber-500/20",
    payWalletBorder: "border-amber-500/20",
    payWalletIconBg: "bg-slate-900",
    payWalletIconText: "text-amber-400",
    logoBorder: "border-amber-500/30",
    langBtnBorder: "border-amber-500/30",
    langBtnBg: "bg-blue-950/60 hover:bg-blue-900/40",
    primaryColor: "text-amber-400",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-white to-slate-300",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme5",
    nameEn: "Theme 5",
    nameAr: "ثيم 5",
    mainBg: "from-rose-950 via-stone-950 to-stone-900",
    linkBg: "bg-rose-900/20 hover:bg-rose-900/30",
    linkBorder: "border-rose-500/20",
    linkHoverBorder: "hover:border-rose-400/50",
    linkText: "text-rose-50",
    payCardBg: "bg-rose-900/10",
    payCardBorder: "border-rose-800/30",
    payInstaBg: "bg-rose-500/10 border border-rose-500/20 hover:bg-rose-500/20",
    payInstaBorder: "border-rose-500/20",
    payInstaIconBg: "bg-rose-500/20",
    payInstaIconText: "text-rose-400",
    payWalletBg: "bg-stone-900/40 border border-rose-500/20",
    payWalletBorder: "border-rose-500/20",
    payWalletIconBg: "bg-stone-950",
    payWalletIconText: "text-rose-400",
    logoBorder: "border-rose-500/30",
    langBtnBorder: "border-rose-500/30",
    langBtnBg: "bg-rose-950/40 hover:bg-rose-900/40",
    primaryColor: "text-rose-400",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-white to-slate-300",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme6",
    nameEn: "Theme 6",
    nameAr: "ثيم 6",
    mainBg: "from-slate-100 via-white to-slate-100",
    linkBg: "bg-white hover:bg-slate-50",
    linkBorder: "border-slate-200/80",
    linkHoverBorder: "hover:border-slate-400/60",
    linkText: "text-slate-800",
    payCardBg: "bg-slate-50",
    payCardBorder: "border-slate-200/80",
    payInstaBg: "bg-slate-100 border border-slate-200 hover:bg-slate-200/50",
    payInstaBorder: "border-slate-200",
    payInstaIconBg: "bg-slate-200",
    payInstaIconText: "text-slate-700",
    payWalletBg: "bg-white border border-slate-200",
    payWalletBorder: "border-slate-200",
    payWalletIconBg: "bg-slate-100",
    payWalletIconText: "text-slate-700",
    logoBorder: "border-slate-200",
    langBtnBorder: "border-slate-200",
    langBtnBg: "bg-white hover:bg-slate-50",
    primaryColor: "text-slate-600",
    textColor: "text-slate-800",
    subTextColor: "text-slate-500",
    companyNameColor: "from-slate-900 to-slate-800",
    cardTitleColor: "text-slate-600",
  },
  {
    key: "theme7",
    nameEn: "Theme 7",
    nameAr: "ثيم 7",
    mainBg: "from-rose-50 via-white to-rose-100",
    linkBg: "bg-white hover:bg-rose-50/50",
    linkBorder: "border-rose-200/80",
    linkHoverBorder: "hover:border-rose-400/60",
    linkText: "text-rose-950",
    payCardBg: "bg-rose-100/30",
    payCardBorder: "border-rose-200/60",
    payInstaBg: "bg-rose-50 border border-rose-200 hover:bg-rose-100/50",
    payInstaBorder: "border-rose-200",
    payInstaIconBg: "bg-rose-100",
    payInstaIconText: "text-rose-700",
    payWalletBg: "bg-white border border-rose-200",
    payWalletBorder: "border-rose-200",
    payWalletIconBg: "bg-rose-50",
    payWalletIconText: "text-rose-700",
    logoBorder: "border-rose-200",
    langBtnBorder: "border-rose-200",
    langBtnBg: "bg-white hover:bg-rose-50/50",
    primaryColor: "text-rose-600",
    textColor: "text-rose-950",
    subTextColor: "text-rose-600",
    companyNameColor: "from-rose-950 to-rose-900",
    cardTitleColor: "text-rose-800",
  },
  {
    key: "theme8",
    nameEn: "Theme 8",
    nameAr: "ثيم 8",
    mainBg: "from-teal-50 via-white to-cyan-50",
    linkBg: "bg-white hover:bg-teal-50/50",
    linkBorder: "border-teal-200/80",
    linkHoverBorder: "hover:border-teal-400/60",
    linkText: "text-teal-950",
    payCardBg: "bg-teal-100/30",
    payCardBorder: "border-teal-200/60",
    payInstaBg: "bg-teal-50 border border-teal-200 hover:bg-teal-100/50",
    payInstaBorder: "border-teal-200",
    payInstaIconBg: "bg-teal-100",
    payInstaIconText: "text-teal-700",
    payWalletBg: "bg-white border border-teal-200",
    payWalletBorder: "border-teal-200",
    payWalletIconBg: "bg-teal-50",
    payWalletIconText: "text-teal-700",
    logoBorder: "border-teal-200",
    langBtnBorder: "border-teal-200",
    langBtnBg: "bg-white hover:bg-teal-50/50",
    primaryColor: "text-teal-600",
    textColor: "text-teal-950",
    subTextColor: "text-teal-600",
    companyNameColor: "from-teal-950 to-teal-900",
    cardTitleColor: "text-teal-800",
  },
  {
    key: "theme9",
    nameEn: "Theme 9",
    nameAr: "ثيم 9",
    mainBg: "from-neutral-900 via-neutral-950 to-neutral-950",
    linkBg: "bg-neutral-900/60 hover:bg-neutral-900",
    linkBorder: "border-amber-500/25",
    linkHoverBorder: "hover:border-amber-400/50",
    linkText: "text-amber-100",
    payCardBg: "bg-amber-950/10",
    payCardBorder: "border-amber-900/40",
    payInstaBg: "bg-amber-500/10 border border-amber-500/25 hover:bg-amber-500/20",
    payInstaBorder: "border-amber-500/25",
    payInstaIconBg: "bg-amber-500/20",
    payInstaIconText: "text-amber-400",
    payWalletBg: "bg-neutral-900 border border-neutral-800",
    payWalletBorder: "border-neutral-800",
    payWalletIconBg: "bg-neutral-950",
    payWalletIconText: "text-amber-400",
    logoBorder: "border-amber-500/25",
    langBtnBorder: "border-amber-500/25",
    langBtnBg: "bg-neutral-900/80 hover:bg-neutral-800",
    primaryColor: "text-amber-400",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-amber-200 to-amber-50",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme10",
    nameEn: "Theme 10",
    nameAr: "ثيم 10",
    mainBg: "from-red-950/40 via-zinc-950 to-red-950/30",
    linkBg: "bg-zinc-900/50 hover:bg-zinc-900",
    linkBorder: "border-red-500/20",
    linkHoverBorder: "hover:border-red-500/50",
    linkText: "text-zinc-100",
    payCardBg: "bg-red-950/10",
    payCardBorder: "border-red-900/30",
    payInstaBg: "bg-red-500/10 border border-red-500/25 hover:bg-red-500/20",
    payInstaBorder: "border-red-500/25",
    payInstaIconBg: "bg-red-500/20",
    payInstaIconText: "text-red-400",
    payWalletBg: "bg-zinc-900 border border-zinc-800",
    payWalletBorder: "border-zinc-800",
    payWalletIconBg: "bg-zinc-950",
    payWalletIconText: "text-red-400",
    logoBorder: "border-red-500/20",
    langBtnBorder: "border-red-500/20",
    langBtnBg: "bg-zinc-900/80 hover:bg-zinc-800",
    primaryColor: "text-red-500",
    textColor: "text-white",
    subTextColor: "text-slate-400",
    companyNameColor: "from-white via-red-200 to-red-100",
    cardTitleColor: "text-slate-300",
  },
  {
    key: "theme11",
    nameEn: "Theme 11",
    nameAr: "ثيم 11",
    mainBg: "from-black via-zinc-950 to-black",
    linkBg: "bg-zinc-900/40 hover:bg-zinc-900/60",
    linkBorder: "border-zinc-800/30",
    linkHoverBorder: "hover:border-zinc-700",
    linkText: "text-white",
    payCardBg: "bg-zinc-900/20",
    payCardBorder: "border-zinc-800/40",
    payInstaBg: "bg-zinc-900/30 border border-zinc-800/40 hover:bg-zinc-800/40",
    payInstaBorder: "border-zinc-800/40",
    payInstaIconBg: "bg-zinc-900",
    payInstaIconText: "text-zinc-100",
    payWalletBg: "bg-zinc-900/30 border border-zinc-800/40",
    payWalletBorder: "border-zinc-800/40",
    payWalletIconBg: "bg-zinc-950",
    payWalletIconText: "text-zinc-100",
    logoBorder: "border-zinc-800",
    langBtnBorder: "border-zinc-800",
    langBtnBg: "bg-zinc-950 hover:bg-zinc-900",
    primaryColor: "text-zinc-400",
    textColor: "text-white",
    subTextColor: "text-zinc-400",
    companyNameColor: "from-white via-zinc-200 to-zinc-400",
    cardTitleColor: "text-zinc-300",
  },
  {
    key: "theme12",
    nameEn: "Theme 12",
    nameAr: "ثيم 12",
    mainBg: "from-zinc-50 via-white to-zinc-100",
    linkBg: "bg-white hover:bg-zinc-50",
    linkBorder: "border-zinc-200/80",
    linkHoverBorder: "hover:border-zinc-300",
    linkText: "text-zinc-900",
    payCardBg: "bg-zinc-50/50",
    payCardBorder: "border-zinc-200/50",
    payInstaBg: "bg-zinc-100/60 border border-zinc-200/60 hover:bg-zinc-100",
    payInstaBorder: "border-zinc-200/60",
    payInstaIconBg: "bg-zinc-200/60",
    payInstaIconText: "text-zinc-700",
    payWalletBg: "bg-white border border-zinc-200/60",
    payWalletBorder: "border-zinc-200/60",
    payWalletIconBg: "bg-zinc-100",
    payWalletIconText: "text-zinc-700",
    logoBorder: "border-zinc-200",
    langBtnBorder: "border-zinc-200",
    langBtnBg: "bg-white hover:bg-zinc-50",
    primaryColor: "text-zinc-500",
    textColor: "text-zinc-900",
    subTextColor: "text-zinc-500",
    companyNameColor: "from-zinc-950 to-zinc-800",
    cardTitleColor: "text-zinc-800",
  },
];

export function getThemeConfig(key: string | null | undefined): ThemeConfig {
  let lookupKey = key;
  if (key === "slate") lookupKey = "theme1";
  else if (key === "emerald") lookupKey = "theme2";
  else if (key === "purple-sunset") lookupKey = "theme3";
  else if (key === "royal-gold") lookupKey = "theme4";
  else if (key === "rose-wine") lookupKey = "theme5";
  
  return THEMES.find((t) => t.key === lookupKey) || THEMES[0];
}
